from django.urls import path

from api import (
    mobile_account,
    mobile_calendar,
    mobile_lists,
    mobile_media,
    views,
)

app_name = "api"

urlpatterns = [
    path(
        "mobile/health/",
        views.mobile_health,
        name="mobile_health",
    ),
    path(
        "search/",
        views.mobile_search,
        name="mobile_search",
    ),
    path(
        "media/add/",
        views.mobile_media_add,
        name="mobile_media_add",
    ),
    path(
        "lists/",
        mobile_lists.mobile_lists,
        name="mobile_lists",
    ),
    path(
        "lists/<int:list_id>/",
        mobile_lists.mobile_list_detail,
        name="mobile_list_detail",
    ),
    path(
        "calendar/",
        mobile_calendar.mobile_calendar,
        name="mobile_calendar",
    ),
    path(
        "calendar/reload/",
        mobile_calendar.mobile_calendar_reload,
        name="mobile_calendar_reload",
    ),
    path(
        "auth/login/",
        views.login,
        name="login",
    ),
    path(
        "auth/logout/",
        views.logout,
        name="logout",
    ),
    path(
        "me/",
        views.me,
        name="me",
    ),
    path(
        "account/",
        mobile_account.mobile_account,
        name="mobile_account",
    ),
    path(
        "account/privacy/",
        mobile_account.mobile_profile_privacy,
        name="mobile_profile_privacy",
    ),
    path(
        "account/password/",
        mobile_account.mobile_change_password,
        name="mobile_change_password",
    ),
    path(
        "home/next-up/",
        views.home_next_up,
        name="home_next_up",
    ),
    path(
        (
            "media/provider/"
            "<str:source>/"
            "<str:media_type>/"
            "<str:media_id>/"
        ),
        mobile_media.mobile_provider_detail,
        name="mobile_provider_detail",
    ),
    path(
        (
            "media/"
            "<str:media_type>/"
            "<int:instance_id>/"
        ),
        mobile_media.mobile_media_detail,
        name="media_detail",
    ),
    path(
        (
            "media/"
            "<str:media_type>/"
            "<int:instance_id>/"
            "progress/"
        ),
        views.media_progress,
        name="media_progress",
    ),
]